### ISSUE TITLE
12 Column Grid - IE Version

### ISSUE THREAD

**Issue by wylie** [ebsco/edna#59]
With the new 12 column grid ( #42 ) we will need to have IE fallback styles for older browsers :cry:

**Comment by wylie** [comment]
It looks like this works fine in IE versions, so this may be completed?

**Comment by gjjones** [comment]
Wasn't the only issue in IE8 that it wouldn't shrink to the single column layout?

**Comment by wylie** [comment]
Yep. The previous version worked by using `:nth-child`, so there was a complicated fallback for that. This didn't need anything like that. Easy peasy.

**Comment by wylie** [comment]
Closing because it works a-okay in IE
