### ISSUE TITLE
Variables Stylesheet

### ISSUE THREAD

**Issue by wylie** [ebsco/edna#94]
The `less/_variables.less` stylesheet can be slimmed down a bit. Consolidate some variables into others, which will need to be carried through to the stylesheets that use these variables.

Too many options = confusion.

**Comment by gjjones** [comment]
I like this one. A lot.

We should talk about this at some point to get an idea of what work is needed.

**Comment by wylie** [comment]
Yep, sounds good. I imagine this will be a time consuming headache of a task, but when it's finished things will be so much better.
